name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Add logging to check the contents of the working directory after checkout
    - name: Debug - List files after checkout
      run: ls -al

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    # Add logging to check Java version
    - name: Debug - Check Java version
      run: java -version

    # Add logging to check Gradle version
    - name: Debug - Check Gradle version
      run: ./gradlew --version

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    # Optional: Add logging to check the build output or additional debugging steps if needed
    - name: Debug - List build directory
      run: ls -al build
